src/Entity/PlatV2.php
<?php

namespace App\Entity;

use App\Repository\PlatV2Repository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlatV2Repository::class)
 */
class PlatV2
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $ingredients;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setIngredients(?string $ingredients): self
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->prix, 2, ',', ' ' );
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

templates/frontend/gerant/add.html.twig
{% extends 'base.html.twig' %}
{% block title 'Admin' %}
{% block body %}
    <h1>Hello
        {{ controller_name }}!
    </h1>
    {{ form_start(form) }}
        {{ form_rest(form) }}
        <button class="btn btn-warning"> Sauvegarder </button>
    {{ form_end(form) }}

    <a href="{{ path('admin') }}" class="btn btn-secondary">Retour à la page Admin</a>
{% endblock %}

templates/frontend/gerant/admin.html.twig
{% extends 'base.html.twig' %}
{% block title 'Admin' %}
{% block body %}

<div class="container" align="center">
    <h2>Plat</h2>
    <div class="row flex">
        {% for plat in plats %}
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="#"> {{ plat.nom}}</a>
                        </h5>
                        <p class="card-text">{{ plat.ingredients }}</p>
                        <div class="text-primary"> {{ plat.formattedPrice }} €</div>
                        <a href="{{ path('edit-plat', {id: plat.id}) }}" class="btn btn-primary stretched-link"> Editer </a> <a href="{{ path('remove-plat', {id: plat.id}) }}" class="btn btn-danger stretched-link"> Supprimer </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <a href="{{ path('add-plat') }}" class="btn btn-secondary">Ajouter un plat</a>
</div>

{% endblock %}